{
 "title": "Content_Repository",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Starts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ComplianceAsCode_content_stargazers_count",
     "legendFormat": "Starts"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ComplianceAsCode_content_forks_count",
     "legendFormat": "Starts"
    }
   ]
  },
  {
   "title": "Organization Infos",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ComplianceAsCode_org_repositories",
     "legendFormat": "Repositories"
    },
    { "expr": "ComplianceAsCode_org_members", "legendFormat": "Members" },
    { "expr": "ComplianceAsCode_org_admins", "legendFormat": "Admins" }
   ]
  },
  {
   "title": "Quick Links",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 0 },
   "options": {
    "content": "* <a href=\"https://github.com/ComplianceAsCode/content\" target=\"_blank\">Code</a>\n* <a href=\"https://github.com/ComplianceAsCode/content/issues\" target=\"_blank\">Issues</a>\n* <a href=\"https://github.com/ComplianceAsCode/content/pulls\" target=\"_blank\">Pull requests</a>\n* <a href=\"https://github.com/ComplianceAsCode/content/discussions\" target=\"_blank\">Discussions</a>\n* <a href=\"https://github.com/ComplianceAsCode/content/actions\" target=\"_blank\">Actions</a>\n* <a href=\"https://github.com/ComplianceAsCode/content/pulse\" target=\"_blank\">Insights</a>\n\n"
   }
  },
  { "title": "Repository Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Open Issues",
   "type": "timeseries",
   "description": "Old Open Issues are only considered when no assignee is defined.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "ComplianceAsCode_content_open_issues_count - ComplianceAsCode_content_open_pulls",
     "legendFormat": "Open Issues"
    },
    {
     "expr": "ComplianceAsCode_content_old_open_issues - ComplianceAsCode_content_old_open_pulls",
     "legendFormat": "Old Open Issues"
    }
   ]
  },
  {
   "title": "Open PRs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 6 },
   "targets": [
    {
     "expr": "ComplianceAsCode_content_open_pulls",
     "legendFormat": "Open PRs"
    },
    {
     "expr": "ComplianceAsCode_content_old_open_pulls",
     "legendFormat": "Old Open PRs"
    }
   ]
  },
  {
   "title": "Contributors vs Subscribers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "ComplianceAsCode_content_contributors",
     "legendFormat": "Contributors"
    },
    {
     "expr": "ComplianceAsCode_content_subscribers_count",
     "legendFormat": "Subscribers"
    }
   ]
  },
  {
   "title": "Labeled Issues",
   "type": "timeseries",
   "description": "Count of issues with specific labels.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "ComplianceAsCode_content_open_issues_label_productizationissue",
     "legendFormat": "productization-issue"
    },
    {
     "expr": "ComplianceAsCode_content_open_issues_label_disarhel9stigalignment",
     "legendFormat": "DISA RHEL9 STIG Alignment"
    },
    {
     "expr": "ComplianceAsCode_content_open_issues_label_needsoktotest",
     "legendFormat": "need-ok-to-test"
    }
   ]
  },
  { "title": "Within last 90 days", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "PRs Balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "ComplianceAsCode_content_created_pulls_90days",
     "legendFormat": "Created PRs"
    },
    {
     "expr": "ComplianceAsCode_content_closed_pulls_90days",
     "legendFormat": "Closed PRs"
    }
   ]
  },
  {
   "title": "PRs Lifetime Average",
   "type": "timeseries",
   "description": "Difference between the PR creation and closing times.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "ComplianceAsCode_content_pulls_lifetime_average",
     "legendFormat": "PRs Lifetime Avg"
    }
   ]
  },
  {
   "title": "Events (activity)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "ComplianceAsCode_content_events",
     "legendFormat": "Number of Events"
    }
   ]
  }
 ]
}