{
 "title": "Content_Policies",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "anssi - minimal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"minimal\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 1 },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"minimal\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"minimal\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_anssi{level=\"minimal\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_anssi{level=\"minimal\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"minimal\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_anssi{level=\"minimal\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_anssi{level=\"minimal\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "anssi - intermediary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"intermediary\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 2 },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"intermediary\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"intermediary\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_anssi{level=\"intermediary\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_anssi{level=\"intermediary\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"intermediary\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_anssi{level=\"intermediary\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_anssi{level=\"intermediary\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "anssi - enhanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"enhanced\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 3 },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"enhanced\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"enhanced\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_anssi{level=\"enhanced\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_anssi{level=\"enhanced\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"enhanced\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_anssi{level=\"enhanced\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_anssi{level=\"enhanced\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "anssi - high",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"high\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 4 },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"high\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"high\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_anssi{level=\"high\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_anssi{level=\"high\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_anssi{level=\"high\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_anssi{level=\"high\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_anssi{level=\"high\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ccn_rhel9 - basic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_ccn_rhel9{level=\"basic\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 7 },
     "targets": [
      {
       "expr": "policy_requirements_status_ccn_rhel9{level=\"basic\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_ccn_rhel9{level=\"basic\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_ccn_rhel9{level=\"basic\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_ccn_rhel9{level=\"basic\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_ccn_rhel9{level=\"basic\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_ccn_rhel9{level=\"basic\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_ccn_rhel9{level=\"basic\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ccn_rhel9 - intermediate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_ccn_rhel9{level=\"intermediate\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 8 },
     "targets": [
      {
       "expr": "policy_requirements_status_ccn_rhel9{level=\"intermediate\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_ccn_rhel9{level=\"intermediate\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_ccn_rhel9{level=\"intermediate\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_ccn_rhel9{level=\"intermediate\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_ccn_rhel9{level=\"intermediate\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_ccn_rhel9{level=\"intermediate\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_ccn_rhel9{level=\"intermediate\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ccn_rhel9 - advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_ccn_rhel9{level=\"advanced\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 9 },
     "targets": [
      {
       "expr": "policy_requirements_status_ccn_rhel9{level=\"advanced\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_ccn_rhel9{level=\"advanced\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_ccn_rhel9{level=\"advanced\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_ccn_rhel9{level=\"advanced\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_ccn_rhel9{level=\"advanced\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_ccn_rhel9{level=\"advanced\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_ccn_rhel9{level=\"advanced\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "cis_rhel9 - l1_server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel9{level=\"l1_server\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 10 },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel9{level=\"l1_server\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel9{level=\"l1_server\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_cis_rhel9{level=\"l1_server\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_cis_rhel9{level=\"l1_server\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel9{level=\"l1_server\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_cis_rhel9{level=\"l1_server\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_cis_rhel9{level=\"l1_server\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "cis_rhel9 - l2_server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel9{level=\"l2_server\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 11 },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel9{level=\"l2_server\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel9{level=\"l2_server\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_cis_rhel9{level=\"l2_server\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_cis_rhel9{level=\"l2_server\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel9{level=\"l2_server\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_cis_rhel9{level=\"l2_server\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_cis_rhel9{level=\"l2_server\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "cis_rhel8 - l1_server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel8{level=\"l1_server\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 12 },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel8{level=\"l1_server\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel8{level=\"l1_server\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_cis_rhel8{level=\"l1_server\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_cis_rhel8{level=\"l1_server\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel8{level=\"l1_server\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_cis_rhel8{level=\"l1_server\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_cis_rhel8{level=\"l1_server\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "cis_rhel8 - l2_server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel8{level=\"l2_server\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 13 },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel8{level=\"l2_server\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel8{level=\"l2_server\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_cis_rhel8{level=\"l2_server\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_cis_rhel8{level=\"l2_server\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel8{level=\"l2_server\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_cis_rhel8{level=\"l2_server\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_cis_rhel8{level=\"l2_server\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "cis_rhel7 - l1_server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel7{level=\"l1_server\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 14 },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel7{level=\"l1_server\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel7{level=\"l1_server\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_cis_rhel7{level=\"l1_server\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_cis_rhel7{level=\"l1_server\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel7{level=\"l1_server\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_cis_rhel7{level=\"l1_server\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_cis_rhel7{level=\"l1_server\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "cis_rhel7 - l2_server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel7{level=\"l2_server\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 15 },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel7{level=\"l2_server\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel7{level=\"l2_server\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_cis_rhel7{level=\"l2_server\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_cis_rhel7{level=\"l2_server\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_cis_rhel7{level=\"l2_server\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_cis_rhel7{level=\"l2_server\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_cis_rhel7{level=\"l2_server\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "pcidss_3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_pcidss_3{level=\"base\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 5 },
     "targets": [
      {
       "expr": "policy_requirements_status_pcidss_3{level=\"base\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_pcidss_3{level=\"base\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_pcidss_3{level=\"base\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_pcidss_3{level=\"base\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_pcidss_3{level=\"base\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_pcidss_3{level=\"base\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_pcidss_3{level=\"base\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "pcidss_4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_pcidss_4{level=\"base\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 15 },
     "targets": [
      {
       "expr": "policy_requirements_status_pcidss_4{level=\"base\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_pcidss_4{level=\"base\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_pcidss_4{level=\"base\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_pcidss_4{level=\"base\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_pcidss_4{level=\"base\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_pcidss_4{level=\"base\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_pcidss_4{level=\"base\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "stig_rhel9 - low",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_stig_rhel9{level=\"low\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 16 },
     "targets": [
      {
       "expr": "policy_requirements_status_stig_rhel9{level=\"low\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_stig_rhel9{level=\"low\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_stig_rhel9{level=\"low\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_stig_rhel9{level=\"low\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_stig_rhel9{level=\"low\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_stig_rhel9{level=\"low\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_stig_rhel9{level=\"low\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "stig_rhel9 - medium",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_stig_rhel9{level=\"medium\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 17 },
     "targets": [
      {
       "expr": "policy_requirements_status_stig_rhel9{level=\"medium\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_stig_rhel9{level=\"medium\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_stig_rhel9{level=\"medium\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_stig_rhel9{level=\"medium\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_stig_rhel9{level=\"medium\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_stig_rhel9{level=\"medium\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_stig_rhel9{level=\"medium\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "stig_rhel9 - high",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "status",
     "type": "piechart",
     "description": "This pie chart shows the latest status of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_stig_rhel9{level=\"high\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "status history",
     "type": "timeseries",
     "description": "This chart shows the status history of all requirements included in the control file.",
     "gridPos": { "h": 9, "w": 11, "x": 7, "y": 18 },
     "targets": [
      {
       "expr": "policy_requirements_status_stig_rhel9{level=\"high\",status!=\"assessed\",status!=\"not assessed\",status!=\"applicable\",status!=\"full coverage\",status!=\"all\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "all requirements",
     "type": "stat",
     "description": "All requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_stig_rhel9{level=\"high\",status=\"all\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "assessed",
     "type": "stat",
     "description": "Assessed requirements are all requirements not in \"pending\" status. It means they were already assessed and properly classified.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_stig_rhel9{level=\"high\", status=\"assessed\"}) / sum by (level) (policy_requirements_status_stig_rhel9{level=\"high\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "applicable requirements",
     "type": "stat",
     "description": "All applicable requirements included in the policy. If the policy contains different levels, the number will represent the number of requirements in selected level.\n\nSome policies may include requirements for different components but make them optional or applicable only in some specific circumstances.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "policy_requirements_status_stig_rhel9{level=\"high\",status=\"applicable\"}",
       "legendFormat": "Existing Labels"
      }
     ]
    },
    {
     "title": "full coverage",
     "type": "stat",
     "description": "full coverage includes all requirements in the following status:\n- automated\n- documentation\n- inherently_met\n- manual\n\nFor more detailed information, check the utils/controleval.py tool in ComplianceAsCode/content repository.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (level) (policy_requirements_status_stig_rhel9{level=\"high\", status=\"full coverage\"}) / sum by (level) (policy_requirements_status_stig_rhel9{level=\"high\", status=\"all\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}